export const LOAD_POPULAR_VIDEO = "LOAD_POPULAR_VIDEO";
export const SEARCH_POPULAR_VIDEO = "SEARCH_POPULAR_VIDEO";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const LOAD_GENRE_LIST = "LOAD_GENRE_LIST";
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";